/* Auto-generated by train.py - do not edit */
#ifndef MODEL_PARAMS_H
#define MODEL_PARAMS_H

/* Input normalization: x_norm = (x_raw - MEAN) / STD */
#define INPUT_DL_MEAN   2.704711f
#define INPUT_DL_STD    9.389182f
#define INPUT_DR_MEAN   7.634644f
#define INPUT_DR_STD    4.579809f

/* Output de-normalization: x_phys = x_norm * STD + MEAN */
#define OUTPUT_EPS_MEAN 0.150595f
#define OUTPUT_EPS_STD  0.086285f
#define OUTPUT_D_MEAN   25.011832f
#define OUTPUT_D_STD    16.470533f

/* Physical clamp bounds */
#define OUTPUT_EPS_MIN  0.0f
#define OUTPUT_EPS_MAX  0.3f
#define OUTPUT_D_MIN    0.0f
#define OUTPUT_D_MAX    50.0f

#endif /* MODEL_PARAMS_H */
