/* Auto-generated by deploy_medium_deep.py  DO NOT EDIT */
/* Stage1: 1->16->8->4->1  Stage2: 2->32->16->8->1  Total 978 params */
#include "nn_inference_md.h"
#include "nn_weights_md.h"
#include "main.h"    /* DWT->CYCCNT */
#include "decoupler_params.h"  /* SC_DR_MEAN etc. */

#ifndef DWT_BASE
#define DWT_BASE ((DWT_Type*)0xE0001000UL)
#endif

void nn_md_init(void) { /* no runtime init needed — weights in Flash/SRAM */ }

NNOutMD nn_md_run(float dL_pct, float dR_pct)
{
    float h0[32], h1[32], h2[32];
    float tmp = 0.0f;

    /* ── Stage1: dR_norm -> eps_norm ── */
    float in_vec[1];
    in_vec[0] = (dR_pct - SC_DR_MEAN) / SC_DR_STD;

    uint32_t t_s1 = DWT->CYCCNT;
    /* Layer 0: 1->16 */
    for (int i = 0; i < 16; i++) {
        int32_t acc = 0;
        for (int j = 0; j < 1; j++)
            acc += (int32_t)S1_W0[i * 1 + j] *
                   (int32_t)(in_vec[j] / S1_W0_SCALE * 127.0f);
        h0[i] = acc * S1_W0_SCALE * S1_W0_SCALE / 127.0f + S1_B0[i];
        if (h0[i] < 0.0f) h0[i] = 0.0f;  /* ReLU */
    }
    /* Layer 1: 16->8 */
    for (int i = 0; i < 8; i++) {
        int32_t acc = 0;
        for (int j = 0; j < 16; j++)
            acc += (int32_t)S1_W1[i * 16 + j] *
                   (int32_t)(h0[j] / S1_W1_SCALE * 127.0f);
        h1[i] = acc * S1_W1_SCALE * S1_W1_SCALE / 127.0f + S1_B1[i];
        if (h1[i] < 0.0f) h1[i] = 0.0f;  /* ReLU */
    }
    /* Layer 2: 8->4 */
    for (int i = 0; i < 4; i++) {
        int32_t acc = 0;
        for (int j = 0; j < 8; j++)
            acc += (int32_t)S1_W2[i * 8 + j] *
                   (int32_t)(h1[j] / S1_W2_SCALE * 127.0f);
        h2[i] = acc * S1_W2_SCALE * S1_W2_SCALE / 127.0f + S1_B2[i];
        if (h2[i] < 0.0f) h2[i] = 0.0f;  /* ReLU */
    }
    /* Layer 3: 4->1 */
    for (int i = 0; i < 1; i++) {
        int32_t acc = 0;
        for (int j = 0; j < 4; j++)
            acc += (int32_t)S1_W3[i * 4 + j] *
                   (int32_t)(h2[j] / S1_W3_SCALE * 127.0f);
        tmp = acc * S1_W3_SCALE * S1_W3_SCALE / 127.0f + S1_B3[i];
    }
    uint32_t cyc_s1 = DWT->CYCCNT - t_s1;

    float eps_pct = tmp * SC_EPS_STD + SC_EPS_MEAN;
    if (eps_pct < 0.0f)  eps_pct = 0.0f;
    if (eps_pct > 30.0f) eps_pct = 30.0f;

    /* ── Stage2: [dL_norm, eps_norm] -> d_norm ── */
    in_vec[0] = (dL_pct - SC_DL_MEAN) / SC_DL_STD;
    in_vec[1] = (eps_pct - SC_EPS_MEAN) / SC_EPS_STD;

    uint32_t t_s2 = DWT->CYCCNT;
    /* Layer 0: 2->32 */
    for (int i = 0; i < 32; i++) {
        int32_t acc = 0;
        for (int j = 0; j < 2; j++)
            acc += (int32_t)S2_W0[i * 2 + j] *
                   (int32_t)(in_vec[j] / S2_W0_SCALE * 127.0f);
        h0[i] = acc * S2_W0_SCALE * S2_W0_SCALE / 127.0f + S2_B0[i];
        if (h0[i] < 0.0f) h0[i] = 0.0f;  /* ReLU */
    }
    /* Layer 1: 32->16 */
    for (int i = 0; i < 16; i++) {
        int32_t acc = 0;
        for (int j = 0; j < 32; j++)
            acc += (int32_t)S2_W1[i * 32 + j] *
                   (int32_t)(h0[j] / S2_W1_SCALE * 127.0f);
        h1[i] = acc * S2_W1_SCALE * S2_W1_SCALE / 127.0f + S2_B1[i];
        if (h1[i] < 0.0f) h1[i] = 0.0f;  /* ReLU */
    }
    /* Layer 2: 16->8 */
    for (int i = 0; i < 8; i++) {
        int32_t acc = 0;
        for (int j = 0; j < 16; j++)
            acc += (int32_t)S2_W2[i * 16 + j] *
                   (int32_t)(h1[j] / S2_W2_SCALE * 127.0f);
        h2[i] = acc * S2_W2_SCALE * S2_W2_SCALE / 127.0f + S2_B2[i];
        if (h2[i] < 0.0f) h2[i] = 0.0f;  /* ReLU */
    }
    /* Layer 3: 8->1 */
    for (int i = 0; i < 1; i++) {
        int32_t acc = 0;
        for (int j = 0; j < 8; j++)
            acc += (int32_t)S2_W3[i * 8 + j] *
                   (int32_t)(h2[j] / S2_W3_SCALE * 127.0f);
        tmp = acc * S2_W3_SCALE * S2_W3_SCALE / 127.0f + S2_B3[i];
    }
    uint32_t cyc_s2 = DWT->CYCCNT - t_s2;

    float d_mm = tmp * SC_D_STD + SC_D_MEAN;
    if (d_mm < 0.0f)  d_mm = 0.0f;
    if (d_mm > 50.0f) d_mm = 50.0f;

    NNOutMD out;
    out.eps_pct  = eps_pct;
    out.d_mm     = d_mm;
    out.d_valid  = (d_mm <= 15.0f) ? 1 : 0;
    out.stage1_us = (float)cyc_s1 / 170.0f;
    out.stage2_us = (float)cyc_s2 / 170.0f;
    return out;
}
