/* Auto-generated by deploy_medium_deep.py  DO NOT EDIT */
#ifndef NN_INFERENCE_MD_H
#define NN_INFERENCE_MD_H

typedef struct {
    float eps_pct;
    float d_mm;
    int   d_valid;
    float stage1_us;
    float stage2_us;
} NNOutMD;

void nn_md_init(void);
NNOutMD nn_md_run(float dL_pct, float dR_pct);

#endif /* NN_INFERENCE_MD_H */
