/* Auto-generated by retrain_moe_v3.py — do not edit by hand.
 * 후보 2(게이트 + EMA 4-input MLP) 배포 상수 — 2026-08-19 재학습본 (v3, sync 버그 수정 후).
 * 데이터: nn_decoupling/test0816_RealtimeDecoupling/moe_monitor_20260819_141013.csv
 * (UART 손상 행 제거 후 25,795행).
 *
 * v2(0817) 대비 바뀐 점:
 *   - 2026-08-18~19에 발견·수정된 moe_realtime_monitor.py의 ground-truth 싱크
 *     버그(STM32 500Hz 스트림을 큐 배치로 몰아서 처리하면서, 배치 안의 과거
 *     STM32 샘플에 "드레인 시점(=미래)"의 Z/Fz를 붙이던 문제) 이후 재수집한
 *     데이터로 학습함. 수정 내역: (1) _pos_hist/_rft_hist 타임스탬프 이력 +
 *     _lookup_nearest()로 각 STM32 샘플 자신의 캡처 시점에 맞는 ground truth를
 *     매칭, (2) STM32Reader가 500Hz 전부를 파싱하지 않고 STM32_KEEP_EVERY_N=5로
 *     다운샘플(실효 100Hz)해서 GIL 경합 상황에서도 못 따라잡는 문제 완화.
 *   - 이번 세션은 ZERO를 접촉 지점 자체에서 잡았다(실측 확인: Z_mm<=-0.2에서
 *     Force_N이 유의미하게 커짐) — 0817의 "25mm 앞에서 영점" 규약과 달리
 *     dist_mm = Z_mm 그대로 쓴다(오프셋 없음), 접촉 판정은 Z_mm<=-0.2.
 *   - 오프라인 held-out 성능: gate acc 94.1%->97.4%, force R² 0.85->0.97
 *     (RMSE 1.77N->0.55N) — 특히 압력 채널이 크게 개선됨. dist R²는 0.92->0.89로
 *     소폭 하락(고변형률(25~30%) 구간에서 인덕턴스 측정이 불안정(Q-factor 저하
 *     추정)해진 영향으로 보임 — realtime_train_seq3_nopress_highstrain.txt로
 *     그 구간 압착 없이 근접만 재수집해 개선 예정).
 *
 * [이전부터 유지] 게이트는 EMA 없이 원본 2-input(dL_pct, dR_pct)만 쓴다.
 * 전문가 A/B는 4-input(EMA 포함) 유지.
 */
#ifndef MOE_PARAMS_H
#define MOE_PARAMS_H

/* ─── 게이트 입력: [dL_pct, dR_pct] (EMA 없음) ────────────────────────────── */
/* ─── 전문가 A/B 입력: [dL_pct, dR_pct, dL_ema, dR_ema] ───────────────────── */

/* 게이트(접촉 분류기) StandardScaler — 2-input */
#define GATE_MEAN_0   -7.514685992150023f
#define GATE_MEAN_1   11.324181756069196f
#define GATE_SCALE_0  13.785563951107491f
#define GATE_SCALE_1  11.841895637407147f

/* 전문가 A(근접, strain+distance) StandardScaler */
#define EA_MEAN_0   -1.3917558052800674f
#define EA_MEAN_1   6.400342617684035f
#define EA_MEAN_2   -1.5017817994107467f
#define EA_MEAN_3   6.372223695838355f
#define EA_SCALE_0  11.986782109409177f
#define EA_SCALE_1  5.252034708117276f
#define EA_SCALE_2  11.582064331636303f
#define EA_SCALE_3  5.245067566210042f

/* 전문가 B(압력, strain+force — force는 양수=누르는 방향) StandardScaler */
#define EB_MEAN_0   -21.388418294033865f
#define EB_MEAN_1   22.480935796803294f
#define EB_MEAN_2   -21.402324814227995f
#define EB_MEAN_3   22.163533715824755f
#define EB_SCALE_0  4.201936499945228f
#define EB_SCALE_1  14.699159660603495f
#define EB_SCALE_2  3.645244799722892f
#define EB_SCALE_3  12.51877826147594f

/* ─── EMA(이력) 피처 — 4.1절 재귀식: y_n = y_(n-1) + alpha*(x_n - y_(n-1)) ──
 * tau = 1.0125s (기존 배포본과 동일 시간상수 유지)
 * TDM_PERIOD_TIME_US = 1000us(1ms) 고정이므로 alpha = 1 - exp(-dt/tau)도
 * 상수로 미리 계산해서 박아넣는다(런타임에 expf() 호출 불필요). */
#define EMA_ALPHA   0.00098717f  /* dt=1ms, tau=1.0125s */

/* ─── 게이트 임계값 ────────────────────────────────────────────────────────── */
#define GATE_CONTACT_THRESHOLD  0.5f  /* P(contact) >= 0.5 -> 압력 모드 */

/* ─── 출력 클램프 범위 (학습 데이터 실측 범위 + 여유) ─────────────────────────── */
#define STRAIN_MIN_PCT  -2.0f
#define STRAIN_MAX_PCT  32.0f
/* 이번 세션 규약: dist_mm = Z_mm 그대로 (오프셋 없음), 0=접촉 25=원거리 */
#define DIST_MIN_MM     -2.0f
#define DIST_MAX_MM     27.0f
/* force 라벨은 "누르면 양수" 규약(실측 범위 -0.38..14.16N) */
#define FORCE_MIN_N     -2.0f
#define FORCE_MAX_N     16.0f

#endif /* MOE_PARAMS_H */
