/* Auto-generated by export_c.py — do not edit */
#ifndef DECOUPLER_H
#define DECOUPLER_H

typedef struct {
    float eps_pct;    /* Strain  ε  [%]   0~30  */
    float d_mm;       /* Proximity d [mm] 0~50  */
    int   d_valid;    /* 1 if d <= PROX_VALID_MM */
} DecouplerOut;

/* float32 inference (PC validation / fallback) */
DecouplerOut decoupler_run_f32(float dL_pct, float dR_pct);

/* INT8 inference (STM32 production) */
DecouplerOut decoupler_run_i8(float dL_pct, float dR_pct);

#endif /* DECOUPLER_H */
