/* Auto-generated by export_c.py — do not edit */
#include "decoupler.h"
#include "decoupler_params.h"
#include "decoupler_weights.h"
#include <math.h>

/* ─── helpers ─────────────────────────────────────────── */
static inline float relu(float x) { return x > 0.0f ? x : 0.0f; }
static inline float clamp(float x, float lo, float hi) {
    return x < lo ? lo : (x > hi ? hi : x);
}

/* y[out] = W[out×in] · x[in] + b[out]  (row-major W) */
static void linear_f32(const float *W, const float *b,
                        const float *x, float *y,
                        int in_sz, int out_sz) {
    for (int i = 0; i < out_sz; i++) {
        float s = b[i];
        const float *row = W + i * in_sz;
        for (int j = 0; j < in_sz; j++) s += row[j] * x[j];
        y[i] = s;
    }
}

/* INT8: y[out] = (W_i8[out×in] · x[in]) * scale + b[out]
   Accumulate in int32 to avoid overflow, then dequantize. */
static void linear_i8(const int8_t *W, float scale, const float *b,
                       const float *x, float *y,
                       int in_sz, int out_sz) {
    for (int i = 0; i < out_sz; i++) {
        int32_t acc = 0;
        const int8_t *row = W + i * in_sz;
        for (int j = 0; j < in_sz; j++)
            acc += (int32_t)row[j] * (int32_t)(x[j] / scale * 127.0f);
        y[i] = acc * scale * scale / 127.0f + b[i];
    }
}

/* ─── float32 inference ───────────────────────────────── */
DecouplerOut decoupler_run_f32(float dL_pct, float dR_pct) {
    float h0[128], h1[128], h2[128];
    float tmp;

    /* ── Stage1: dR_norm → eps_norm ── */
    float dR_n = (dR_pct - SC_DR_MEAN) / SC_DR_STD;
    linear_f32(S1_W0_F32, S1_B0_F32, &dR_n, h0, 1, 128);
    for(int i=0;i<128;i++) h0[i]=relu(h0[i]);
    linear_f32(S1_W1_F32, S1_B1_F32, h0, h1, 128, 128);
    for(int i=0;i<128;i++) h1[i]=relu(h1[i]);
    linear_f32(S1_W2_F32, S1_B2_F32, h1, h2, 128, 64);
    for(int i=0;i<64;i++) h2[i]=relu(h2[i]);
    linear_f32(S1_W3_F32, S1_B3_F32, h2, &tmp, 64, 1);

float eps_pct = tmp * SC_EPS_STD + SC_EPS_MEAN;
eps_pct = clamp(eps_pct, EPS_MIN_PCT, EPS_MAX_PCT);

/* ── Stage2: [dL_norm, eps_norm] → d_norm ── */
float dL_n   = (dL_pct - SC_DL_MEAN) / SC_DL_STD;
float eps_n  = (eps_pct - SC_EPS_MEAN) / SC_EPS_STD;
float x2[2] = {dL_n, eps_n};
    linear_f32(S2_W0_F32, S2_B0_F32, x2, h0, 2, 128);
    for(int i=0;i<128;i++) h0[i]=relu(h0[i]);
    linear_f32(S2_W1_F32, S2_B1_F32, h0, h1, 128, 128);
    for(int i=0;i<128;i++) h1[i]=relu(h1[i]);
    linear_f32(S2_W2_F32, S2_B2_F32, h1, h2, 128, 64);
    for(int i=0;i<64;i++) h2[i]=relu(h2[i]);
    linear_f32(S2_W3_F32, S2_B3_F32, h2, &tmp, 64, 1);

    float d_mm = tmp * SC_D_STD + SC_D_MEAN;
    d_mm = clamp(d_mm, D_MIN_MM, D_MAX_MM);

    DecouplerOut out;
    out.eps_pct = eps_pct;
    out.d_mm    = d_mm;
    out.d_valid = (d_mm <= PROX_VALID_MM) ? 1 : 0;
    return out;
}

/* ─── INT8 inference ─────────────────────────────── */
DecouplerOut decoupler_run_i8(float dL_pct, float dR_pct) {
    float h0[128], h1[128], h2[128];
    float tmp;
    float dR_n = (dR_pct - SC_DR_MEAN) / SC_DR_STD;
    linear_i8(S1_W0_I8, S1_W0_SCALE, S1_B0_I8F, &dR_n, h0, 1, 128);
    for(int i=0;i<128;i++) h0[i]=relu(h0[i]);
    linear_i8(S1_W1_I8, S1_W1_SCALE, S1_B1_I8F, h0, h1, 128, 128);
    for(int i=0;i<128;i++) h1[i]=relu(h1[i]);
    linear_i8(S1_W2_I8, S1_W2_SCALE, S1_B2_I8F, h1, h2, 128, 64);
    for(int i=0;i<64;i++) h2[i]=relu(h2[i]);
    linear_i8(S1_W3_I8, S1_W3_SCALE, S1_B3_I8F, h2, &tmp, 64, 1);
    float eps_pct=clamp(tmp*SC_EPS_STD+SC_EPS_MEAN,EPS_MIN_PCT,EPS_MAX_PCT);
    float dL_n=(dL_pct-SC_DL_MEAN)/SC_DL_STD;
    float eps_n=(eps_pct-SC_EPS_MEAN)/SC_EPS_STD;
    float x2[2]={dL_n,eps_n};
    linear_i8(S2_W0_I8, S2_W0_SCALE, S2_B0_I8F, x2, h0, 2, 128);
    for(int i=0;i<128;i++) h0[i]=relu(h0[i]);
    linear_i8(S2_W1_I8, S2_W1_SCALE, S2_B1_I8F, h0, h1, 128, 128);
    for(int i=0;i<128;i++) h1[i]=relu(h1[i]);
    linear_i8(S2_W2_I8, S2_W2_SCALE, S2_B2_I8F, h1, h2, 128, 64);
    for(int i=0;i<64;i++) h2[i]=relu(h2[i]);
    linear_i8(S2_W3_I8, S2_W3_SCALE, S2_B3_I8F, h2, &tmp, 64, 1);
    float d_mm=clamp(tmp*SC_D_STD+SC_D_MEAN,D_MIN_MM,D_MAX_MM);
    DecouplerOut o; o.eps_pct=eps_pct; o.d_mm=d_mm; o.d_valid=(d_mm<=PROX_VALID_MM)?1:0;
    return o;
}
