/* Auto-generated by export_c.py — do not edit */
#ifndef DECOUPLER_PARAMS_H
#define DECOUPLER_PARAMS_H

/* ─── Input / Output Scalers ──────────────────────── */
#define SC_DR_MEAN   9.13018514f
#define SC_DR_STD    5.46861368f
#define SC_DL_MEAN   6.44144908f
#define SC_DL_STD    8.00288380f
#define SC_EPS_MEAN  15.00106726f
#define SC_EPS_STD   8.60225755f
#define SC_D_MEAN    18.31689259f
#define SC_D_STD     10.47814133f
#define LOG_D        0

/* ─── Output clamp bounds ─────────────────────────── */
#define EPS_MIN_PCT  0.0f
#define EPS_MAX_PCT  30.0f
#define D_MIN_MM     0.0f
#define D_MAX_MM     50.0f
#define PROX_VALID_MM 15.0f

/* ─── Architecture: Stage1 ────────────────────────── */
#define S1_N_LAYERS  4
#define S1_L0_IN  1
#define S1_L0_OUT 128
#define S1_L1_IN  128
#define S1_L1_OUT 128
#define S1_L2_IN  128
#define S1_L2_OUT 64
#define S1_L3_IN  64
#define S1_L3_OUT 1

/* ─── Architecture: Stage2 ────────────────────────── */
#define S2_N_LAYERS  4
#define S2_L0_IN  2
#define S2_L0_OUT 128
#define S2_L1_IN  128
#define S2_L1_OUT 128
#define S2_L2_IN  128
#define S2_L2_OUT 64
#define S2_L3_IN  64
#define S2_L3_OUT 1

#endif /* DECOUPLER_PARAMS_H */
